### ISSUE TITLE
maps/fusioncharts.india.js' cannot be loaded as its extension is not registered in assetExts

### ISSUE THREAD

**Issue by bhavinatharva** [fusioncharts/react-native-fusioncharts#161]
All other fusions charts are loading, expect map charts 

```
"react-native-fusioncharts": "4.1.2"
"fusioncharts": "3.13.4"
"react-native": "0.61.3"
"react": "16.11.0"
```
<img width="278" alt="Screenshot 2022-07-12 at 8 15 17 PM" src="https://user-images.githubusercontent.com/84075780/178518104-ed172c25-fc12-4111-96e3-0b523a9367d6.png">

it is working fine in android, but not working in ios
```
Error: 'fusioncharts.india.js' cannot be loaded as its extension is not registered in assetExts
    at /Users/sample-react-native/src/node_modules/metro/src/Assets.js:356:13
    at Generator.next (<anonymous>)
![Simulator Screen Shot - iPhone 11 - 2022-07-12 at 20 14 58](https://user-images.githubusercontent.com/84075780/178518063-59ceda46-dfa6-412e-b3bb-b52e8bf2e62c.png)

    at asyncGeneratorStep (/Users/bhavinparghi/Workspace/ReactNativeWorkspace/sample-react-native/src/node_modules/metro/src/Assets.js:52:24)
    at _next (/Users/bhavinparghi/Workspace/ReactNativeWorkspace/sample-react-native/src/node_modules/metro/src/Assets.js:72:9)
    at /Users/bhavinparghi/Workspace/ReactNativeWorkspacesample-react-native/src/node_modules/metro/src/Assets.js:77:7
    at new Promise (<anonymous>)
    at /Users/bhavinparghi/Workspace/ReactNativeWorkspace/sample-react-native/src/node_modules/metro/src/Assets.js:69:12
    at getAsset (/Users/bhavinparghi/Workspace/ReactNativeWorkspace/sample-react-native/src/node_modules/metro/src/Assets.js:337:20)
    at /Users/bhavinparghi/Workspace/ReactNativeWorkspace/sample-react-native/src/node_modules/metro/src/Server.js:992:28
    at Generator.next (<anonymous>)
::1 - - [12/Jul/2022:14:35:36 +0000] "GET /assets/maps/fusioncharts.india.js HTTP/1.1" 404 - "http://localhost:8081/assets/fusioncharts.html?platform=ios&hash=9be20ec8f9e73309304cf97b510c2076" "Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
````

**Comment by AyanBhadury** [comment]
Hey,

Save the file from this cdn, manually place it in the assets folder, and reference it in the HTML file.

https://cdn.fusioncharts.com/fusioncharts/3.20.0/maps/fusioncharts.india.js
