### ISSUE TITLE
Duplicate module name: fusioncharts

### ISSUE THREAD

**Issue by huuthinh245** [fusioncharts/react-native-fusioncharts#46]
### **ERROR**
Loading dependency graph...(node:43012) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: fusioncharts
  Paths: /Users/thinh/Documents/xaydung/android/app/build/intermediates/merged_assets/debug/mergeDebugAssets/out/fusioncharts/package.json collides with /Users/thinh/Documents/xaydung/android/app/src/main/assets/fusioncharts/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/thinh/Documents/xaydung/node_modules/jest-haste-map/build/index.js:569:17)
    at workerReply (/Users/thinh/Documents/xaydung/node_modules/jest-haste-map/build/index.js:641:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:43012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:43012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:43012) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: fusioncharts
  Paths: /Users/thinh/Documents/xaydung/android/app/build/intermediates/merged_assets/debug/mergeDebugAssets/out/fusioncharts/package.json collides with /Users/thinh/Documents/xaydung/android/app/src/main/assets/fusioncharts/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/thinh/Documents/xaydung/node_modules/jest-haste-map/build/index.js:569:17)
    at workerReply (/Users/thinh/Documents/xaydung/node_modules/jest-haste-map/build/index.js:641:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:43012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
::ffff:127.0.0.1 - - [06/May/2019:06:22:30 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 870 "-" "okhttp/3.12.1"
Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: fusioncharts
  Paths: /Users/thinh/Documents/xaydung/android/app/build/intermediates/merged_assets/debug/mergeDebugAssets/out/fusioncharts/package.json collides with /Users/thinh/Documents/xaydung/android/app/src/main/assets/fusioncharts/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/thinh/Documents/xaydung/node_modules/jest-haste-map/build/index.js:569:17)
    at workerReply (/Users/thinh/Documents/xaydung/node_modules/jest-haste-map/build/index.js:641:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
### **ENVIRONMENT**
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 425.26 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v11.10.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.3 => 0.59.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.4.1
### **VERSION**
    "fusioncharts": "^3.13.4",
    "react-native-fusioncharts": "^3.0.0",
    "react": "16.8.3",
    "react-native": "0.59.3",

**Comment by rohanoid5** [comment]
Hey @huuthinh245 I was not able to replicate this error. These are the package version I am using:
```
"fusioncharts": "^3.13.4",
"react": "16.8.3",
"react-native": "0.59.5",
"react-native-fusioncharts": "^3.0.0"
```

Can you let me know when you are facing this error? More specifically after which point of the setup you came about to these problem?

And can you try deleting the `package.json` file from `/Users/thinh/Documents/xaydung/android/app/src/main/assets/fusioncharts/` and try rebuilding the project to see if the error persists or not?

**Comment by huuthinh245** [comment]
@rohanoid5 After delete package.json  in /Users/thinh/Documents/xaydung/android/app/src/main/assets/fusioncharts/
It throw the new error 
error: bundling failed: Error: ENOENT: no such file or directory, scandir '/Users/thinh/Documents/xaydung/src/screens/chart/task/assets'
    at Object.readdirSync (fs.js:806:3)
    at Object.getDirFiles (/Users/thinh/Documents/xaydung/node_modules/metro/src/node-haste/DependencyGraph.js:103:34)
    at Map.AssetResolutionCache.dirPath [as _factory] (/Users/thinh/Documents/xaydung/node_modules/metro/src/node-haste/AssetResolutionCache.js:41:36)
    at Map.get (/Users/thinh/Documents/xaydung/node_modules/metro/src/node-haste/lib/MapWithDefaults.js:23:24)
    at AssetResolutionCache.resolve (/Users/thinh/Documents/xaydung/node_modules/metro/src/node-haste/AssetResolutionCache.js:91:43)
    at resolveAsset (/Users/thinh/Documents/xaydung/node_modules/metro/src/node-haste/DependencyGraph.js:229:36)
    at resolveAssetFiles (/Users/thinh/Documents/xaydung/node_modules/metro-resolver/src/resolve.js:463:22)
    at resolveFile (/Users/thinh/Documents/xaydung/node_modules/metro-resolver/src/resolve.js:349:20)
    at resolveFileOrDir (/Users/thinh/Documents/xaydung/node_modules/metro-resolver/src/resolve.js:262:22)
    at resolveModulePath (/Users/thinh/Documents/xaydung/node_modules/metro-resolver/src/resolve.js:184:18)

**Comment by huuthinh245** [comment]
@rohanoid5  after delete package.json. Everything is working. Thank you so much.

**Comment by Himitris** [comment]
Same error but the @rohanoid5 solution didn't work for me
